"""Markdown bulletin formatting node.

Emits `digest_status` alongside the markdown (FR-903). Routing keys off
that field, never off emptiness: "no new articles" and "the ranker
returned nothing usable" are different states, and only the first is a
green no-op. FR-905 adds the `invalid` value for a malformed response.

Also emits `digest_html` from the same story list — no markdown parser,
no new dependency. The archive stays markdown; the mail carries both, so
recipients see rendered links instead of raw `[title](url)`.
"""

import logging
from html import escape

from yamlgraph.contrib import to_serializable

logger = logging.getLogger(__name__)


def format_markdown(state: dict) -> dict:
    """Render ranked stories as a markdown bulletin."""
    today = state.get("today", "")
    ranked_stories = state.get("ranked_stories", [])

    if hasattr(ranked_stories, "stories"):
        ranked_stories = ranked_stories.stories
    ranked_stories = to_serializable(ranked_stories) if ranked_stories else []
    if isinstance(ranked_stories, dict):
        ranked_stories = ranked_stories.get("stories", [])

    if not ranked_stories:
        logger.info("📝 No stories to format — nothing to report today")
        return {
            "digest_markdown": "",
            "digest_html": "",
            "digest_status": "no_articles",
        }

    lines = [f"# Daily Tech Digest — {today}", ""]
    html = [
        "<html><body style=\"font-family:-apple-system,BlinkMacSystemFont,"
        "'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;"
        "padding:20px;line-height:1.5\">",
        f"<h1 style=\"border-bottom:2px solid #007acc;padding-bottom:8px\">"
        f"Daily Tech Digest — {escape(today)}</h1>",
    ]
    for story in ranked_stories:
        title = story.get("title", "Untitled")
        url = story.get("url", "")
        summary = story.get("summary", "")
        reason = story.get("reason", "")
        lines.append(f"## [{title}]({url})")
        if summary:
            lines.append(f"\n{summary}")
        if reason:
            lines.append(f"\n*Why: {reason}*")
        lines.append("")

        # escape(): titles and summaries are model output, not trusted markup
        html.append(
            f'<h2 style="font-size:1.1em;margin:24px 0 6px">'
            f'<a href="{escape(url, quote=True)}" '
            f'style="color:#007acc;text-decoration:none">{escape(title)}</a></h2>'
        )
        if summary:
            html.append(f'<p style="color:#333;margin:6px 0">{escape(summary)}</p>')
        if reason:
            html.append(
                f'<p style="color:#777;font-style:italic;margin:6px 0">'
                f"📌 {escape(reason)}</p>"
            )

    lines.append("---")
    lines.append(
        "*Generated by [YAMLGraph](https://pypi.org/project/yamlgraph/) "
        "running unattended in GitHub Actions.*"
    )
    html.append(
        '<hr style="margin-top:28px;border:0;border-top:1px solid #ddd">'
        '<p style="color:#888;font-size:0.85em">Generated by '
        '<a href="https://pypi.org/project/yamlgraph/">YAMLGraph</a> '
        "running unattended in GitHub Actions.</p></body></html>"
    )

    logger.info(f"📝 Formatted bulletin with {len(ranked_stories)} stories")
    return {
        "digest_markdown": "\n".join(lines) + "\n",
        "digest_html": "\n".join(html),
        "digest_status": "ready",
    }
