"""Markdown bulletin formatting node.

Emits `digest_status` alongside the markdown (FR-903). Routing keys off
that field, never off emptiness: "no new articles" and "the ranker
returned nothing usable" are different states, and only the first is a
green no-op. FR-905 adds the `invalid` value for a malformed response.

Also emits `digest_html` from the same story list — no markdown parser,
no new dependency. The archive stays markdown; the mail carries both, so
recipients see rendered links instead of raw `[title](url)`.
"""

import logging
from html import escape

from pydantic import BaseModel, ValidationError

from yamlgraph.contrib import to_serializable

logger = logging.getLogger(__name__)


class InvalidRankedStoriesError(RuntimeError):
    """The ranker ran and produced nothing usable.

    Distinct from a quiet day: `no_articles` means the ranker was never
    invoked. This means it was, and its output cannot be trusted — so the
    run fails loudly instead of committing an empty bulletin.
    """


class RankedStory(BaseModel):
    """The shape `prompts/rank_stories.yaml` asks for but cannot enforce.

    `stories: list[Any]` constrains the array, not its elements, so this
    is where the contract is actually applied.
    """

    title: str
    url: str
    summary: str = ""
    reason: str = ""
    relevance: float | None = None


def _validate(raw: list) -> list[RankedStory]:
    """Keep conforming stories; log every drop with index and type."""
    kept: list[RankedStory] = []
    for index, item in enumerate(raw):
        try:
            kept.append(RankedStory.model_validate(item))
        except ValidationError as exc:
            reason = exc.errors()[0]["msg"] if exc.errors() else "invalid"
            logger.warning(
                "drop ranked story %d: %s (%s)",
                index,
                type(item).__name__,
                reason[:80],
            )
    return kept


def format_markdown(state: dict) -> dict:
    """Render ranked stories as a markdown bulletin."""
    today = state.get("today", "")
    ranked_stories = state.get("ranked_stories", [])

    if hasattr(ranked_stories, "stories"):
        ranked_stories = ranked_stories.stories
    # A dict payload means the ranker answered, even if its list is empty.
    ranker_answered = isinstance(ranked_stories, dict)
    ranked_stories = to_serializable(ranked_stories) if ranked_stories else []
    if isinstance(ranked_stories, dict):
        ranked_stories = ranked_stories.get("stories", [])

    if not ranked_stories and not ranker_answered:
        logger.info("📝 No stories to format — nothing to report today")
        return {
            "digest_markdown": "",
            "digest_html": "",
            "digest_status": "no_articles",
        }

    observed = sorted({type(item).__name__ for item in ranked_stories})
    stories = _validate(ranked_stories)
    if not stories:
        raise InvalidRankedStoriesError(
            f"digest_status=invalid: ranker returned {len(ranked_stories)} "
            f"item(s) of type(s) {observed or ['none']}, none conforming to "
            f"RankedStory. Refusing to emit an empty bulletin as success."
        )
    ranked_stories = [s.model_dump() for s in stories]

    lines = [f"# Daily Tech Digest — {today}", ""]
    html = [
        "<html><body style=\"font-family:-apple-system,BlinkMacSystemFont,"
        "'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;"
        "padding:20px;line-height:1.5\">",
        f"<h1 style=\"border-bottom:2px solid #007acc;padding-bottom:8px\">"
        f"Daily Tech Digest — {escape(today)}</h1>",
    ]
    for story in ranked_stories:
        title = story.get("title", "Untitled")
        url = story.get("url", "")
        summary = story.get("summary", "")
        reason = story.get("reason", "")
        lines.append(f"## [{title}]({url})")
        if summary:
            lines.append(f"\n{summary}")
        if reason:
            lines.append(f"\n*Why: {reason}*")
        lines.append("")

        # escape(): titles and summaries are model output, not trusted markup
        html.append(
            f'<h2 style="font-size:1.1em;margin:24px 0 6px">'
            f'<a href="{escape(url, quote=True)}" '
            f'style="color:#007acc;text-decoration:none">{escape(title)}</a></h2>'
        )
        if summary:
            html.append(f'<p style="color:#333;margin:6px 0">{escape(summary)}</p>')
        if reason:
            html.append(
                f'<p style="color:#777;font-style:italic;margin:6px 0">'
                f"📌 {escape(reason)}</p>"
            )

    lines.append("---")
    lines.append(
        "*Generated by [YAMLGraph](https://pypi.org/project/yamlgraph/) "
        "running unattended in GitHub Actions.*"
    )
    html.append(
        '<hr style="margin-top:28px;border:0;border-top:1px solid #ddd">'
        '<p style="color:#888;font-size:0.85em">Generated by '
        '<a href="https://pypi.org/project/yamlgraph/">YAMLGraph</a> '
        "running unattended in GitHub Actions.</p></body></html>"
    )

    logger.info(f"📝 Formatted bulletin with {len(ranked_stories)} stories")
    return {
        "digest_markdown": "\n".join(lines) + "\n",
        "digest_html": "\n".join(html),
        "digest_status": "ready",
    }
