"""Markdown bulletin formatting node."""

import logging

from yamlgraph.contrib import to_serializable

logger = logging.getLogger(__name__)


def format_markdown(state: dict) -> dict:
    """Render ranked stories as a markdown bulletin."""
    today = state.get("today", "")
    ranked_stories = state.get("ranked_stories", [])

    if hasattr(ranked_stories, "stories"):
        ranked_stories = ranked_stories.stories
    ranked_stories = to_serializable(ranked_stories) if ranked_stories else []
    if isinstance(ranked_stories, dict):
        ranked_stories = ranked_stories.get("stories", [])

    if not ranked_stories:
        logger.info("📝 No stories to format — no-op bulletin")
        return {"digest_markdown": ""}

    lines = [f"# Daily Tech Digest — {today}", ""]
    for story in ranked_stories:
        title = story.get("title", "Untitled")
        url = story.get("url", "")
        summary = story.get("summary", "")
        reason = story.get("reason", "")
        lines.append(f"## [{title}]({url})")
        if summary:
            lines.append(f"\n{summary}")
        if reason:
            lines.append(f"\n*Why: {reason}*")
        lines.append("")
    lines.append("---")
    lines.append(
        "*Generated by [YAMLGraph](https://pypi.org/project/yamlgraph/) "
        "running unattended in GitHub Actions.*"
    )

    logger.info(f"📝 Formatted markdown bulletin with {len(ranked_stories)} stories")
    return {"digest_markdown": "\n".join(lines) + "\n"}
